version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eddig24
      POSTGRES_DB: BookDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookapi
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=BookDb;Username=postgres;Password=eddig24"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: bookfrontend
    depends_on:
      - api
    ports:
      - "4200:80"

volumes:
  pgdata:
